# Generated by Django 5.2.5 on 2025-10-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tag_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tag_icons/', verbose_name='Іконка тегу'),
        ),
    ]
