# Generated by Django 5.2.5 on 2025-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='icon',
        ),
        migrations.AddField(
            model_name='tag',
            name='icon_class_fa',
            field=models.CharField(blank=True, max_length=50, verbose_name='CSS-клас іконки'),
        ),
    ]
