# Generated by Django 5.2.5 on 2025-10-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_tag_icon_tag_icon_class_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='icon_class_fa',
        ),
    ]
