# Generated by Django 5.2.5 on 2025-10-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_tag_icon_class_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='class_fa',
            field=models.CharField(blank=True, max_length=100, verbose_name='CSS клас іконки FontAwesome'),
        ),
    ]
