# Generated by Django 5.2.5 on 2025-10-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tag_class_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='class_fa',
        ),
        migrations.AddField(
            model_name='tag',
            name='material_icon',
            field=models.CharField(default='tag', max_length=50),
        ),
    ]
