# Generated by Django 5.2.5 on 2025-10-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_tag_class_fa_tag_material_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
