# Generated by Django 5.2.5 on 2025-11-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_remove_image_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="next_todo",
            field=models.BooleanField(default=False, verbose_name="Зроблю наступними"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="material_icon",
            field=models.CharField(max_length=50),
        ),
    ]
